id: P191D2BFA
initial_creation_type: input
source_metadata:
  title: Samten Lingpa Series
  language: en
  description: 'Texts by and about Samten Lingpa Trinle Drodül Lerab Dewa Tsal (bsam
    gtan gling pa ''phrin las ''gro ''dul las rab bde ba rtsal, b. 1871?), who was
    active in the nineteenth century:'
  volume:
    3ff61e812fa245c8b431fa24d4394989:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Prayers
created_at: '2022-03-01T01:28:54.085136'
last_modified_at: '2022-03-01T01:28:54.085143'
